atk4/data

docs/conditions.rst, docs/model.rst, src/Model.php, src/Persistence_SQL.php, tests/ConditionSQLTest.php, tests/ConditionTest.php
Finally, implementation of conditions is complete. And It's AWESOME!
resolve #28
=> Implemented SQL conditions

.codeclimate.yml, .travis.yml, CHANGELOG.md, docs/index.rst, docs/model.rst, docs/persistence.rst, src/Field_Many.php, src/Field_One.php, src/Field_SQL_One.php, src/Join.php, src/Join_SQL.php, src/Model.php, src/Persistence.php, src/Persistence_SQL.php, tests/LimitOrderTest.php, tests/PersistentSQLTest.php, tests/RandomTest.php, tests/RelationSQLTest.php
Review and merge #43 before merging this.
=> Implement setLimit(), setOrder() and export().

docs/results.rst, src/Field.php, src/Model.php, src/Persistence_SQL.php, tests/IteratorTest.php, tests/LimitOrderTest.php
=> Implement iterator

README.md, docs/design.rst, docs/expressions.rst, docs/overview.rst, docs/quickstart.rst, docs/relations.rst
Reviewed:
* readme
* docs/overview
* docs/quickstart
* docs/design
=> Review 2016-07-19

docs/relations.rst, src/Field.php, src/Field_SQL_One.php, src/Model.php
- imprved: hasMany()->addfields(['foo','bar']);
- fix: addCondition('foo', ['a','b']) no longer sets default.
- addField(new Field(), 'name')) displays proper error (you should use add() here)
- docs bugfix
=> Some Minor improvements. 

CHANGELOG.md, docs/quickstart.rst, src/Field.php, src/Field_One.php, src/Model.php, src/Persistence_SQL.php, src/Relation_Many.php, src/Relation_One.php, src/Relation_SQL_One.php
* rename classes Field_One, Field_Many and Field_SQL_One to Relation_x
* related changes in docs
=> Feature/rename classes etc.

docs/conditions.rst, docs/design.rst, docs/expressions.rst, docs/joins.rst, docs/model.rst, docs/quickstart.rst, docs/references.rst, src/Join_SQL.php, src/Reference_One.php, src/Reference_SQL_One.php, src/Relation_Many.php, src/Relation_One.php, src/Relation_SQL_One.php
* added Relation_* classes for backward compatibility
* changes in addTitle() - fixes #137 
* syntax of SQL blocks in docs - fixes #76
=> Backward compatibility of Reference classes, changes in addTitle, syntax in docs

src/Model.php
allow beforeUpdate hook to break execution also.
beforeInsert and beforeSave hooks already does that
=> allow beforeUpdate hook to break execution

src/Join.php
init method was renamed in wrong Trait
=> Bug Fix, rename init in proper Trait

CHANGELOG.md, docs/references.rst, src/Model.php, tests/ReferenceTest.php
=> Implement Model::addRef()

src/Model.php, src/Persistence_Array.php
* fix data[0] = &array() error
* fix #245
=> Fix array persistence data error

src/Field.php
Minor improvements to make it work with 1.3
=> Feature/fix core 1.3

src/Persistence_SQL.php
=> Fix initQueryFields (274)

src/Model.php
=> works better with namespaces

.travis.yml, phpunit-mysql.xml, phpunit-pgsql.xml, tests/ConditionSQLTest.php, tests/ExpressionSQLTest.php, tests/FieldTest.php, tests/JoinSQLTest.php, tests/ModelWithoutIDTest.php, tests/RandomTest.php, tests/ReferenceSQLTest.php, tests/SQLTestCase.php, tests/Structure.php, tests/TypecastingTest.php, tests/smbo/SMBOTestCase.php, tests/smbo/TransferTest.php
Add travis testing on both mysql and postgresql, see #288 
- the tests are running now, but some fail on mysql, others fail on pgsql. Will look into that. @
=> Travis db testing

src/Field.php, src/Persistence.php
We should use `ValidationException` instead of `Exception` when we talk about validating field values.
=> use ValidationException

docs/model.rst, src/Model.php, src/Persistence_Static.php, tests/RandomTest.php
* implements `$caption`, `getModelCaption()`, `getTitle()`
* add test coverage
* fix #289, fix #290
* add documentation
* bugfix for cases when id_field is not set at all
=> Implement caption, getTitle, getModelCaption

src/Persistence.php
* use normalizeDSN()
* fix #298
=> use normalizeDSN()

src/Reference_SQL_One.php, tests/RandomTest.php
=> Fix addTitle()

docs/design.rst, docs/joins.rst
* fix #204
* few more corrections in documentation
=> fix some docs

src/Model.php, src/Persistence_SQL.php, tests/ConditionSQLTest.php, tests/LimitOrderTest.php, tests/PersistentSQLTest.php, tests/RandomTest.php
* implement exportById(), fix #311
* cleanup
=> Implement export() with field values used as array keys

src/Model.php
see https://github.com/atk4/data/pull/295/files/a4820af0f494f97ff09c3be77047f5a2e5730545#r182140710
=> fix newInstance()

src/Field/Boolean.php, src/Model.php, tests/RefactoredFieldTest.php
Implements types:
- boolean
Example:
``` php
$model->addField('is_vip', ['type'=>'boolean']);
$model->addField('is_vip', ['type'=>'boolean', 'enum'=>['No', 'Yes']);
```
=> Implement Field\Boolean

README.md, docs/field_boolean.rst, docs/types.rst
Some initial documentation for #308. Early feedback is welcome!!
=> Add some initial documentation

docs/hooks.rst
$m->set() does not work in these hooks, added note about this. It was a unclear to me as in other hooks data is altered using $m->set()
=> beforeInsert/beforeUpdate Note

src/Reference_SQL_One.php, tests/ConditionSQLTest.php, tests/ReferenceSQLTest.php
* fix #370
* fix hasOne() lookup field change / save
* add extensive test to cover all that
* remove useles and wrong beforeSave hook set by init method
=> Fix Reference_SQL_One lookup bugs, adds tests

src/Join.php, tests/JoinSQLTest.php
* add test for Join->hasOne/hasMany (also improves coverage a bit)
* fix Join->hasOne/hasMany methods
* fully fix #369 issue
=> Fix Join->hasOne/hasMany

docs/fields.rst, docs/typecasting.rst, src/Field/Callback.php, src/Model.php, tests/FieldHereditaryTest.php
Fix default addExpression seed in model + remove FieldCallback constructor as $expr is now set with the $seed.
=> Fix problem with addExpression on models with Persistence_Array

src/Field.php, tests/TypecastingTest.php
=> Fix #389 Field Time after save wrong return value

docs/references.rst
Old branch, but looks still relevant.
=> Dark side666 patch 1

docs/persistence.rst
Checking if field value is unique: The condition has to be that the id of the new Instance IS NOT the id of the original record.
=> Fix logic error in example

src/Field.php
Now, working fine
a small precedence bug.
=> Nesty BUG. was still returning wrong

src/Reference/ContainsMany.php, src/Reference/ContainsOne.php, tests/ContainsManyTest.php, tests/ContainsOneTest.php
fix #451 
fix #452 
required by https://github.com/atk4/ui/pull/784
=> containsOne/Many changes for UI

src/Model.php, tests/TransactionTest.php
resolve #460 
Credit to @PhilippGrashoff and @acicovic
=> add is_update flag on beforeSave Hook!

.github/workflows/php.yml, .travis.yml, phpunit-mysql-workflow.xml, phpunit-pgsql-workflow.xml, tests/FieldTypesTest.php
Implementation of GitHub actions. Will compare them against TravisCI to see which one is more robust and easier to use.
=> Implement GitHub action support

.github/workflows/changelog.yml, .github/workflows/php.yml, .github/workflows/release.yml, phpunit-pgsql-workflow.xml
Add pgsql workflow to github actions
=> Add pgsql workflow

.github/workflows/unit-tests.yml, locale/en/atk.php, locale/ru/atk.php, tests/LocaleTest.php
Another test for verifying language selection for error messages.
=> added locale test

.github/workflows/bundler.yml
=> clean up bundler

src/Model.php
i think its a bug preventing the model from using extended default_add_field class
=> model default add field property

locale/en/atk.php, locale/it/atk.php, locale/ru/atk.php, src/Join.php, src/Model.php, src/Persistence/SQL.php, src/Reference.php, src/Reference/ContainsMany.php, src/Reference/ContainsOne.php, src/Reference/HasMany.php, src/Reference/HasOne.php, src/Reference/HasOne_SQL.php, src/Util/DeepCopy.php, tests/CSVTest.php, tests/ConditionSQLTest.php, tests/JoinSQLTest.php, tests/ReferenceSQLTest.php, tests/TypecastingTest.php
fix #496 
rely on https://github.com/atk4/dsql/pull/165
=> Fix empty array condition

src/Model.php, src/UserAction/Generic.php
- Set Edit action exec button label to 'Save' by default
- Set Edit action exec button color to blue by default
- Set default description for Add action in model
- Add method to retrieve the model from Action
=> Fix/ Small Action related fix

docs/model.rst
`deleteAll` method has been removed
=> update multiple delete example in docs

docs/advanced.rst, docs/design.rst, docs/hooks.rst, docs/model.rst, docs/overview.rst, docs/persistence.rst, src/Field/Callback.php, src/Field_SQL_Expression.php, src/Join.php, src/Join/Array_.php, src/Join/SQL.php, src/Model.php, src/Persistence/Static_.php, src/Reference/ContainsMany.php, src/Reference/ContainsOne.php, src/Reference/HasOne.php, src/Reference/HasOne_SQL.php, tests/DeepCopyTest.php, tests/FieldTest.php, tests/JoinSQLTest.php, tests/LookupSQLTest.php, tests/RandomTest.php, tests/SubTypesTest.php, tests/TransactionTest.php, tests/ValidationTest.php, tests/smbo/lib/Transfer.php
related to https://github.com/atk4/ui/issues/966
=> [REFACTOR] rename addHook to onHook

src/Join/Array_.php, src/Join/SQL.php, src/Reference/HasOne.php, src/Reference/HasOne_SQL.php
=> Fix hook trait usage

src/Action/Iterator.php, src/Model.php, src/Persistence/Array_.php, src/Persistence/SQL.php, tests/ConditionSQLTest.php, tests/PersistentArrayTest.php
=> Fix LIKE conditions for Array and SQL persistences

src/Action/Iterator.php
=> Fix value trim

src/Persistence/SQL.php, tests/ConditionSQLTest.php
=> introduce sql null condition test

src/Field.php, src/Field_SQL.php, src/Field_SQL_Expression.php, src/Join.php, src/Join/SQL.php, src/Model.php, src/Reference.php, src/UserAction/Generic.php, src/Util/DeepCopy.php
Important for quick navigation and refactoring.
=> Fix refactorability for "owner"
